# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: borg-backup-remotely
    main: './cmd/backup'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    goarm:
      - '6'
      - '7'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}


dockers:
- image_templates:
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-amd64"
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-amd64"
  use: buildx
  goarch: amd64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"

- image_templates:
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-i386"
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-i386"
  use: buildx
  goarch: '386'
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/386"

- image_templates:
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-arm64v8"
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"

- image_templates:
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-armv7"
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-armv7"
  use: buildx
  goarch: arm
  goarm: 7
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"

- image_templates:
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-armv6"
  - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-armv6"
  use: buildx
  goarch: arm
  goarm: 6
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v6"

docker_manifests:
  - id: "backup"
    name_template: "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}"
    image_templates:
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-amd64"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-i386"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-arm64v8"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-armv7"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Version }}-armv6"
  - id: "backup-major"
    name_template: "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}"
    image_templates:
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-amd64"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-i386"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-arm64v8"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-armv7"
    - "ghcr.io/swat-engineering/borg-backup-remotely:{{ .Major }}-armv6"


changelog:
  sort: asc
  filters:
    exclude:
      - "^\\[ci\\].*"
      - "^\\[test\\].*"
      - "^\\[chore\\].*"
